### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/hacker-typing#11]
* [x] hacker typing
* [x] quit with <kbd>⎋ Escape</kbd> or <kbd>⌃ Control</kbd><kbd>c</kbd>
* [x] `-speed N`: type N chars for each keypress
* [x] loop at the end of the file
* [x] `--autotype`
* [ ] support `-` for STDIN
* [ ] support passing multiple files
* [ ] support dirs
* [ ] support binary files
* [ ] support <kbd>⌫ Delete</kbd>
* [ ] `--rainbow-chars`, `--rainbow-lines`
* [ ] `--zalgo`
* [ ] `--matrix`
* [ ] `--random-beeps`
* [ ] `--random-emojis`
* [ ] `--random-erase`
* [ ] `--demo` (predefined dictionary with hacker words)
